# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: David Wernhart
title: Software Developer
email: david.wernhart96@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  davidwernhart
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: davidwernhart
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Hello there!
    My name is David and I like to tinker with computers. At the age of 14, I built my first functional CPU out of logic components from inside a video game, with my excitement and expertise about this topic only growing since then.
    
    My current primary fields of expertise are: <mark>Game Development</mark> (Unity, LibGdx), <mark>App Development</mark> (Flutter) and <mark>Computer Vision</mark> (TensorFlow, OpenCV).

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other hobbies include:
   - Skateboarding
   - Gaming
   - [Making music](https://www.instagram.com/pinqinband/)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
